# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b3345c65b4e1dda61be6956c9e0d6edb0a989e4376b420ff0c1e5da6ba6ddb936309bdae1d8111189a0840599301faf4006ae795e16c73a637d667c34aa5124

test:
  secret_key_base: a505c5bf1c98194dfd567f5336dd7a24d150c04968340945c28cba04f1c9efad9d69538aafc13eec341f613faf5d467c7dd8d8afdabfba33d9680fc254505089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
